redpanda-data/terraform-provider-redpanda

.github/CODEOWNERS, redpanda/resources/acl/resource_acl.go, redpanda/resources/cluster/resource_cluster.go, redpanda/resources/namespace/resource_namespace.go, redpanda/resources/user/resource_user.go
This commit fixes a bug where the user was not able to update `allow_deletion` in the cluster resource.
When updating `Computed` attributes Terraform will treat them as 'changing' attributes and trigger an error. To solve this we add the plan modifier as recommended by Terraform:
>  Use the [resource.UseStateForUnknown() attribute plan modifier](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/resource#UseStateForUnknown) for Computed attributes that are known to not change during resource updates. This will enhance the Terraform plan to not show => (known after apply) differences.
Also implementing `Update` in the cluster resource as a passthrough from plan -> state due to:
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to …
```
=> [bugfix] allow cluster updates

redpanda/models/redpanda.go, redpanda/redpanda.go, redpanda/redpanda_test.go
These should be supported later, but we should
remove them from now since the auto-generated
docs will pick them up.
=> [chore] Remove unused attributes of Redpanda provider

redpanda/resources/topic/resource_topic.go
Now we provide a hint on what to do if the user
encounters the TOPIC_ALREADY_EXISTS error.
Fixes #65 
We are changing from:
```
│ Error: failed to create topic "asdf"
│ 
│   with redpanda_topic.asdf,
│   on example-data.tf line 27, in resource "redpanda_topic" "asdf":
│   27: resource "redpanda_topic" "asdf" {
│ 
│ rpc error: code = Internal desc = The topic has already been created
```
To:
```
│ Error: Failed to create topic; topic "asdf" already exists
│ 
│   with redpanda_topic.asdf,
│   on example-data.tf line 27, in resource "redpanda_topic" "asdf":
│   27: resource "redpanda_topic" "asdf" {
│ 
│ Topic resource can be imported using 'terraform import redpanda_topic.<resource_name> <topic_name>,<cluster_id>'
```
=> topic: provide hint when the topic already exists

redpanda/resources/topic/resource_topic.go
Redpanda v23.3.12 contains a fix for the
default configuration handling of the
cleanup.policy property.
See: https://github.com/redpanda-data/redpanda/pull/17719
=> topic: remove cleanup.policy filtering

examples/datasource/main.tf, redpanda/resources/topic/resource_topic.go, redpanda/tests/acceptance_test.go, redpanda/utils/utils.go
Previous to this change, a removal of a config
from the state would not make the config to
reset to the cluster default value.
=> topic config: support removal of state configs

docs/data-sources/cluster.md, docs/index.md, docs/resources/cluster.md, examples/cluster/aws/main.tf, examples/cluster/gcp/main.tf, examples/datasource/main.tf, examples/provider.tf
Provider, region, and zones is not yet supported
to be configured at the provider level, instead
it should be configured in network/cluster.
This commit also runs terraform fmt in all .tf
files
=> [bug] Remove unsupported properties from provider config docs

.goreleaser.yaml
Version is now a required field, and v2 deprecated the `changelog.skip` field. Enabling this for now.
=> [chore] Update .goreleaser.yaml

.github/workflows/release.yml
jira: https://redpandadata.atlassian.net/browse/PESDLC-1554
github secrets for this repo have been migrated to aws secretsmanager. this PR uses gha [aws-actions/aws-secretsmanager-get-secrets](https://github.com/aws-actions/aws-secretsmanager-get-secrets) to access the secrets.
=> gha: modify release to use aws sm

.golangci.yml, Makefile, docs/index.md, docs/resources/cluster.md, examples/bulk-data/README.md, examples/bulk-data/main.tf, examples/bulk-res/README.md, examples/bulk-res/main.tf, examples/cluster/aws/main.tf, go.mod, go.sum, redpanda/cloud/cloud.go, redpanda/cloud/ratelimiter.go, redpanda/cloud/ratelimiter_test.go, redpanda/tests/acceptance_test.go
https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers#name-ratelimit-header-field-defi
Relevant RFC used on the API side. I also added a bulk test case and info on what it's doing there. 
Fixes #108
=> Add support for Cloud's new rate limit headers 

redpanda/resources/cluster/resource_cluster.go, redpanda/resources/serverlesscluster/resource_serverless_cluster.go
[This](https://github.com/redpanda-data/cloudv2/pull/16130/commits/c1fc6e1a852b653af832a416615443dba7e85f7b#diff-4b4a8e677856278bcb41f45226b72c24a27cbe8e5033093ebd4ce6a4e7f4ab13) cloud PR ensures that resourceId and metadata are returned in the initial operation response on create operations (createCluster and createServerlessCluster). Given this improvement, it is no longer necessary to poll until the operation is complete to get the metadata in the terraform provider.
=> cloud: remove extra polling on long running create operations

.github/workflows/release.yml
fixes warning when goreleaser job is run:
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe.
> For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
e.g. https://github.com/redpanda-data/terraform-provider-redpanda/actions/runs/10202429395
the v5.0.0 [release](https://github.com/actions/setup-go/releases) of setup-go uses node20 and v5.0.2 is the latest
=> gha: fix node16 warn

redpanda/resources/network/resource_network.go
Networks usually come up within seconds, this was only adding unneeded delay.
=> fix: speed up network creation/deletion checking of op status from 1m to 1s

redpanda/cloud/controlplane.go, redpanda/resources/resourcegroup/data_resourcegroup.go
Useful when just grabbing the "default" resource group. Lets you do stuff like:
```terraform
data "redpanda_resource_group" "default" {
name = "default"
}
resource "redpanda_network" "main" {
name = "arctic-monkey7"
resource_group_id = data.redpanda_resource_group.default.id
cloud_provider = "aws"
region = "ca-central-1"
cluster_type = "cloud"
cidr_block = "10.0.0.0/20"
}
```
=> Feature: Allow looking up resource_group data source by name

Makefile
Happens after rebuilding the plugin with a different checksum
=> fix: Make rule tf-init should delete lockfile to avoid checksum errors

.github/workflows/docs.yml, .github/workflows/release.yml
jira: [PESDLC-1740]
update gha workflows to use [oidc](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) to retrieve secrets
[PESDLC-1740]: https://redpandadata.atlassian.net/browse/PESDLC-1740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> gha: update to use oidc

redpanda/resources/cluster/resource_cluster.go, redpanda/utils/utils.go, redpanda/utils/utils_test.go
The CreateCluster call itself will validate the throughput tiers already, so this is just extra work. This also will work if CreateCluster ever changes its own internal validation logic.
=> chore: don't validate throughput tier when creating cluster

redpanda/resources/network/data_network.go, redpanda/resources/network/network.go, redpanda/resources/network/resource_network.go
* **fix: set network resource state from api response, not plan**: This will catch any cases where the API response doesn't match instead
of silently ignoring it.
* **feat: network data source reads all attributes**: add `cidr_block`, `cloud_provider`, `cluster_type`, `region`, and `resource_group_id` to the network data source
* **chore: extract network.generateModel()**: extracts the "Network API Response to Terraform model" logic which is duplicated in three places into its own file, following the same pattern as the Cluster resource
=> Fixes to network resource and data source state

redpanda/resources/cluster/cluster.go, redpanda/resources/cluster/data_cluster.go, redpanda/resources/cluster/resource_cluster.go, redpanda/resources/cluster/resource_cluster_test.go, redpanda/utils/utils.go, redpanda/utils/utils_test.go
Avoid error checking all over the place when it can be done safely.
=> feat: TestingOnlyStringSliceToTypeList -> StringSliceToTypeList

redpanda/utils/utils.go, redpanda/utils/utils_test.go
When calling it on actual strings, the string gets quoted and special characters like newlines are escaped. It was trimming the quotes but not fixing escaped characters. This was messing up passing mTLS PEM-format certificates, which contain newlines.
Change the logic if called on a types.List that has actual types.String values so we keep the exact string value. Ideally this function is somehow typed so it can only ever be called on types.List that have strings but that seems like a bigger project.
=> fix: pass mTLS certificates correctly (TypeListToStringSlice shouldn't quote special characters)

redpanda/redpanda.go
Fixes a cred failure caused by the provider incorrectly failing with client id and client secret pulled from a secret manager.
=> Fix Inappropriate Failure on Credentials

.goreleaser.yaml, Makefile
Makes goreleaser verbose so we can see the errors and properly converts the gpg key from base64.
Also fixes gpg was attempting to ask for the passphrase with an interactive request. This method of invoking it via goreleaser's config file prevents that.
From the manpage:
If this command is used with --batch, --pinentry-mode has been set to loopback, and one of the passphrase options (--passphrase, --passphrase-fd, or
--passphrase-file) is used, the supplied passphrase is used for the new key and the agent does not ask for it.
=> ci: fix automated release

redpanda/cloud/cloud.go
Set metadata instead of appending to the context, so we ensure only one value is set
=> fix: set user-agent instead of appending

docs/index.md, redpanda/models/redpanda.go, redpanda/redpanda.go
Adds the various config vars needed for byoc/byovpc that weren't already available as config vars (but were available as environment vars) to the config struct for redpanda.
=> feat: add config vars

docs/resources/cluster.md, redpanda/redpanda.go, redpanda/utils/byoc.go, templates/resources/cluster.md.tmpl
Fix for #196 
Adds support for authenticating with Azure via the Azure CLI, and should provide support for managed and workload identities as well.
I'd also suggest removing support for `AZURE_*` environment variables and standardizing on the same `ARM_*` variables used by the Terraform azurerm provider. I've left that out of this PR for the sake of getting CI to pass.
=> feat: support all Azure auth methods for BYOC

Makefile, examples/byovpc/gcp/main.tf, redpanda/resources/cluster/data_cluster.go
Adds GCP CMR datasource elements in the cluster datasource schema that were missing and causing trouble. 
Tested the datasource element successfully.
=> fix: add missing gcp cmr elements

redpanda/resources/topic/resource_topic.go, redpanda/resources/topic/schema_resource.go
Switched to set from add, made it so that decreasing partitions causes destruction and recreate. For deletion and recreate you must enable allow_deletion=true, it is disabled by default.
=> fix: partition issue solved

redpanda/validators/cidr.go
When using a variable for the `cidr_block` attribute in the network resource, validation will always fail due to the initial validation pass using an `Unknown` value. Without adding this guard, the value always gets interpreted as an empty string and fails the regex check.
=> Add IsUnknown guard for CIDR validation

redpanda/resources/network/data_network.go
This adds some necessary fields to the data model of GCP. Currently using `data.redpanda_network` with the provider errors out with the cleaned up following error:
```
Expected framework type from provider logic:
types.ObjectType[
"aws":  types.ObjectType[
"dynamodb_table":types.ObjectType[
"arn":basetypes.StringType
],
"management_bucket":types.ObjectType[
"arn":basetypes.StringType
],
"private_subnets":types.ObjectType[
"arns":types.ListType[basetypes.StringType]
],
"vpc":types.ObjectType[
"arn":basetypes.StringType
]
]
]
...
Received framework type from provider logic:
types.ObjectType[
"aws":types.ObjectType[
"dynamodb_table":types.ObjectType[
"arn":basetypes.StringType
],
"management_bucket":types.ObjectType[
"arn":basetypes.StringType
],
"private_subnets":types.ObjectType[ …
```
=> Add GCP-related fields to the data model for network

Makefile, docs/data-sources/network.md, docs/resources/cluster.md, docs/resources/topic.md, examples/byovpc/gcp/main.tf, examples/datasource/network/main.tf, redpanda/redpanda.go, redpanda/resources/cluster/schema_resource.go, redpanda/resources/network/data_network.go, redpanda/resources/network/network.go, redpanda/resources/network/network_test.go, redpanda/tests/acceptance_test.go
Cloud provider was being incorrectly set in the call to generate model from the model instead of from the network response. As the user cannot provide cloud_provider in the datasource declaration model will likely always have a null value for cloud_provider. This meant that the generate_model function was skipping the GCP element and continuing to the default response (generating a null cmr object) which was incorrect. 
The fix was to pull the relevant cloud_provider value from the API response and use that. I've verified that everything works as intended and added an example. I will come back and add CI for this when I find a good long running byovpc network to take advantage of it.
=> Fix Network Datasource CMR Issue

redpanda/resources/cluster/model_to_proto.go
During the march to 1.0.0 Kafka Connect's return was bugged which caused innumerable issues for the provider necessitating the disabling of its management. This bug has now been resolved and so we no longer need this little piece of code which did so much.
=> Allow modifying Kafka Connect

docs/resources/acl.md
In the docs it implies MATCH is a valid option for resource_pattern_type - however cloud will only take LITERAL,  PREFIXED or ANY
=> Update ACL doc 

docs/data-sources/cluster.md, docs/resources/cluster.md, redpanda/models/cluster/data_model.go, redpanda/models/cluster/data_model_test.go, redpanda/models/cluster/object_definitions.go, redpanda/models/cluster/resource_model.go, redpanda/models/cluster/resource_model_test.go, redpanda/resources/cluster/schema_datasource.go, redpanda/resources/cluster/schema_resource.go
Adds in Cluster Configuration support. Also adds the first take at a consistency test comparing plan and apply -- because most of the sources of provider inconsistency are because the apply phase returns one thing and the plan phase returns anotehr -- as part of the process. This is currently a proof of concept, I hope to generate something more robust and automated for comparison purposes in future (say taking advantage of the golden file testing from k8s operator and outputting the plan and apply models/proto structures to yaml files for comparison).
=> cluster: add support for cluster_configuration

docs/data-sources/cluster.md, docs/resources/cluster.md, redpanda/resources/cluster/schema_datasource.go, redpanda/resources/cluster/schema_resource.go
This pull request adds a warning that modifying the `throughput_tier` property after creation will destroy and recreate the cluster.
Fixes https://redpandadata.atlassian.net/browse/DOC-1578
=> DOC-1578 Update TF docs that changing throughput_tier destroys cluster

redpanda/resources/acl/acl_test.go, redpanda/resources/acl/resource_acl.go
fixes #275 
The problem was that the id field was defined in the schema but never being set in the Create and Read methods.
Changes:
1. Create method: Added composite ID generation using all the ACL fields that uniquely identify an ACL
2. Read method: Added the same composite ID generation to maintain consistency
3. Related unit tests
The composite ID format is: resource_type:resource_name:resource_pattern_type:principal:host:operation:permission_type
This ensures that:
- The ID field will always have a valid string value after planning
- Tools like upjet can properly cast the ID to a string
- The ID is deterministic and consistent across Create/Read operations
- The ID uniquely identifies each ACL resource combination
The fix follows the same pattern used in other resources like role …
=> Generate ACL id field
